---
- hosts: Client
  become: true
  tasks:

  - name: Create folders for scripts
    ansible.builtin.shell:
      cmd: mkdir /root/scripts

  - name: Copy script borg-backup.sh
    ansible.builtin.copy:
      src: ./files/borg-backup.sh
      dest: /root/scripts/borg-backup.sh
      owner: root
      mode: 0770

  - name: Create job in cron for Borg backup
    ansible.builtin.cron:
      name: "Borg backup"
      minute: "*/5"
      hour: "*"
      day: "*"
      month: "*"
      weekday: "*"
      job: "/root/scripts/borg-backup.sh"
