---
- hosts: All
  become: yes
  tasks:

  - name: Copy timezone
    ansible.builtin.copy:
      src: /usr/share/zoneinfo/Europe/Moscow
      dest: /etc/localtime
      owner: root

  - name: Restart chronyd
    ansible.builtin.systemd:
      name: chronyd
      state: restarted
      enabled: yes

  - name: Update the rpm
    ansible.builtin.dnf:
      name:
        - rpm
      state: latest
      update_only: yes

  - name: Enabled powertools
    ansible.builtin.shell:
      cmd: dnf config-manager --set-enabled powertools

  - name: Install epel-release
    ansible.builtin.dnf:
      name: epel-release
      state: present

  - name: Install borgbackup
    ansible.builtin.dnf:
      name: borgbackup
      state: present

- hosts: Server-backup
  become: true
  tasks:

  - name: Create a new ext4 partition
    community.general.parted:
      device: /dev/sdb
      number: 1
      state: present
      fs_type: ext4

  - name: Create folder backup
    ansible.builtin.shell:
      cmd: echo "/dev/sdb1 /var/backup ext4     defaults        0 0" >> /etc/fstab

  - name: Add the user borg
    ansible.builtin.user:
      name: borg
      comment: User for backup

  - name: Create folder backup                                              
    ansible.builtin.shell:
      cmd: mkdir /var/backup && mkfs.ext4 /dev/sdb1 && mount /dev/sdb1 /var/backup/ && chown borg:borg /var/backup/

  - name: Create .ssh
    ansible.builtin.shell:
      cmd: mkdir /home/borg/.ssh && chown borg:borg /home/borg/.ssh && chmod 700 /home/borg/.ssh  

  - name: Copy authorized_keys
    ansible.builtin.copy:
      src: ./files/id_rsa.pub
      dest: /home/borg/.ssh/authorized_keys
      owner: borg
      mode: 0600

- hosts: Client
  become: true
  tasks:

  - name: Create .ssh           
    ansible.builtin.shell:
      cmd: mkdir /root/.ssh

  - name: Copy id_rsa
    ansible.builtin.copy:
      src: ./files/id_rsa
      dest: /root/.ssh/id_rsa
      owner: root
      mode: 0600

  - name: Copy id_rsa.pub
    ansible.builtin.copy:
      src: ./files/id_rsa.pub 
      dest: /root/.ssh/id_rsa.pub
      owner: root
      mode: 0644
